### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by riverar** [riverar/mach2#1]
Mach2 requires very little, in the way of dependencies. Setting this up on AppVeyor, VSO, or similar should be a breeze.

**Comment by AaronFriel** [comment]
I'd like to synchronize this repo to my GitLab instance and try to build it there. Might be a bit interesting because I don't have a Windows build environment yet, but it's on my to-do list. 

If you wanted to allow me to sync the repo, I'd need a webhook set up to point at my [`Grapple`](`https://github.com/aaronfriel/grapple) instance.

**Comment by riverar** [comment]
Sure thing, let's go for it. We can sync offline if any private details need to be exchanged (rafael@withinwindows.com).

**Comment by riverar** [comment]
So, this turned out to be much simpler than I thought; AppVeyor was amazingly simple. VSO was a bloody nightmare.

**Comment by Biswa96** [comment]
Can it be compiled with mingw and makefile?
